### PR TITLE
fix(GuildChannelType): add missing `GuildCategory` type

### LINKED ISSUE #577: `GuildChannelType` does not include category channels
**Please describe the problem you are having in as much detail as possible:**
`GuildChannelType` does not include category channels:

https://github.com/discordjs/discord-api-types/blob/04b3a7f066bd715897fa5eadb940b926f317ecc3/payloads/v10/channel.ts#L42-L56

**Include a reproducible code sample here, if possible:**

```ts
import { ChannelType, GuildChannelType } from "discord-api-types/v10";

declare const guildChannelType: GuildChannelType;

if (ChannelType.GuildCategory === guildChannelType) {
  // This condition will always return 'false'
}
```

**Further details:**

- Runtime:
  
  - Node.js version: 18.8.0
  - deno version: N/A
- Priority this issue should have – please be realistic and elaborate if possible: Medium

### PR DESCRIPTION
**Pull request by Mateo-tem**
**Please describe the changes this PR makes and why it should be merged:**
Closes #577

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

### CODE REVIEW

File: deno/payloads/v10/channel.ts [hunk 1]
```diff
@@ -51,7 +51,11 @@ export type TextChannelType =
 	| ChannelType.GuildVoice;
 
 export type GuildChannelType = Exclude<
-	TextChannelType | ChannelType.GuildVoice | ChannelType.GuildStageVoice | ChannelType.GuildAnnouncement,
+	| TextChannelType
```
Comment (vladfrangu) [inline deno/payloads/v10/channel.ts:54]: Couldn't this just do Exclude<ChannelType, AllTheDMChannelsTypes>?

**Review by vladfrangu — CHANGES_REQUESTED** [review]

File: deno/payloads/v10/channel.ts (hunk 1 above)
Comment (Mateo-tem) [reply deno/payloads/v10/channel.ts:54]: Oh, yes. That makes more sense

**Review by Jiralite — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
