### PR TITLE
fix: correct types for autocomplete interaction data

### LINKED ISSUE #230: Incorrect autocomplete data typings
**Please describe the problem you are having in as much detail as possible:**

It seems like the Autocomplete types are incorrect/incomplete, if it is indeed incorrect, I'm willing to make a PR, if nobody else does.

**Include a reproducible code sample here, if possible:**

```ts
import { APIInteraction, InteractionType } from 'discord-api-types/v9';

const interaction: APIInteraction = {} as APIInteraction;
if (interaction.type === InteractionType.ApplicationCommandAutocomplete) {
    // Property 'options' does not exist on type 'APIApplicationCommandInteractionData'.
    //  Property 'options' does not exist on type 'APIUserApplicationCommandInteractionData'.
    interaction.data?.options;
}
```

I expect i should be able to do this:
```ts
interaction.data?.options[0]?.value // string | number | undefined
```

**Further details:**

NodeJS Version: v16.9.1
discord-api-types Version: 0.25.0-next.bc1d03e.1635987681

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

Closes #230

### CODE REVIEW

File: payloads/v8/_interactions/autocomplete.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
-import type { APIApplicationCommandInteractionData, APIBaseInteraction, InteractionType } from '../index';
+import type { APIBaseInteraction, APIChatInputApplicationCommandInteractionData, InteractionType } from '../index';
 
 export type APIApplicationCommandAutocompleteInteraction = APIBaseInteraction<
 	InteractionType.ApplicationCommandAutocomplete,
-	APIApplicationCommandInteractionData
+	APIChatInputApplicationCommandInteractionData
```
Comment (vladfrangu) [inline payloads/v8/_interactions/autocomplete.ts:5]: This doesn't feel like the right type for this..

**Review by vladfrangu — CHANGES_REQUESTED** [review]

File: payloads/v8/_interactions/autocomplete.ts (hunk 1 above)
Comment (suneettipirneni) [reply payloads/v8/_interactions/autocomplete.ts:5]: I might be reading this wrong, but isn't this correct? 
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure

Comment (vladfrangu) [reply payloads/v8/_interactions/autocomplete.ts:5]: Just checked, it's fine

**Review by vladfrangu — APPROVED** [review]
